/**
 * Sidecar frida
 *
 * Huan <zixia@zixia.net>, June 25, 2021
 *  https://github.com/huan/sidecar
 */
export * from 'frida'
export {
  ScriptMessageHandler,
  ScriptDestroyedHandler,
}                           from 'frida/dist/script'

/**
 * Huan(202106):
 *  - type: agent
 *    A label for the frida target address
 *    This is for the dynamic purpose,
 *    i.e. we need to call/hook a PTR that generated by the init agent.
 *  - type: objc:
 *    ??
 *  - type: module
 *    loadModule('libc', 'open')
 *
 * See: Jumping to Labels in Inline Assembly
 *  https://docs.microsoft.com/en-us/cpp/assembler/inline/jumping-to-labels-in-inline-assembly
 *
 */
export type FunctionTargetType =  'address' // memory address
                                | 'agent'   // frida agent ptr variable name
                                | 'java'    // TODO:
                                | 'module'  // TODO:
                                | 'name'    // library function name
                                | 'objc'    // TODO:
export interface FunctionTargetWrapper {
  type   : FunctionTargetType
  target : string
}

/**
 * Frida Target
 *
 *  number: memory address of the function
 *    - 0x1234
 *
 *  string: export name of the function
 *    - lib: 'open'
 *    - ObjC: '- connection:didReceiveData:'
 */
export type FunctionTargetLink =  number
                                | string

export type FunctionTarget =  FunctionTargetLink
                            | FunctionTargetWrapper

function normalizeFunctionTarget (
  functionTarget: FunctionTarget,
): FunctionTargetWrapper {
  if (typeof functionTarget === 'number') {
    return {
      target : '0x' + Number(functionTarget).toString(16),
      type   : 'address',
    }
  } else if (typeof functionTarget === 'string') {
    return {
      target : functionTarget,
      type   : 'name',
    }
  }
  return functionTarget
}

/**
 * NativeFunction
 *  https://frida.re/docs/javascript-api/#nativefunction
 */
export type NativeType =  'void'
                        | 'pointer'
                        | 'int'
                        | 'uint'
                        | 'long'
                        | 'ulong'
                        | 'char'
                        | 'uchar'
                        | 'size_t'
                        | 'ssize_t'
                        | 'float'
                        | 'double'
                        | 'int8'
                        | 'uint8'
                        | 'int16'
                        | 'uint16'
                        | 'int32'
                        | 'uint32'
                        | 'int64'
                        | 'uint64'
                        | 'bool'

/**
 * NativePointer
 *  https://frida.re/docs/javascript-api/#nativepointer
 */
export type PointerType = 'Pointer'
                        | 'S8'
                        | 'U8'
                        | 'S16'
                        | 'U16'
                        | 'S32'
                        | 'U32'
                        | 'Short'
                        | 'UShort'
                        | 'Int'
                        | 'UInt'
                        | 'Float'
                        | 'Double'
                        | 'S64'
                        | 'U64'
                        | 'Long'
                        | 'ULong'
                        | 'ByteArray'
                        | 'CString'
                        | 'Utf8String'
                        | 'Utf16String'
                        | 'AnsiString'

export type TypeChain = [NativeType, ...PointerType[]]

export {
  normalizeFunctionTarget,
}
